dist: xenial
os: linux
git:
  depth: 3 

language: node_js
node_js:
  - 12

jobs:
  include:
    # ======== Parte del frontend ========
    - language: node_js
      node_js:  '12'

      warnings_are_errors: false

      cache: 
        directories:
          - node_modules

      branches:
        only:
          - master

      before_install: 
        - cd frontend/
        - CI=false 

      install:
        - npm install
      script:
        - npm test && codecov
        - npm run build
      deploy:
        provider: firebase
        skip_cleanup: true
        token: $FIRE_TOKEN

    # ======== Parte de Backend ========
    - language: python
      python:
        - "3.6"

      cache: pip

      branches:
        only:
          - master

      env:
        - DJANGO=3.0

      before_install:
        - cd backend/

      install:
        - "pip install -r requirements.txt"

      script: 
        - python manage.py test

      deploy:
        provider: heroku
        api_key: $HEROKU_TOKEN
        app: univalleapp
        on: 
          repo: Daniel0205/WWW-Proyecto 
          branch: master

   