version: '2.0'
services:

  client:
    image: client
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - server
    container_name: front

  server:

    image: back
    ports:
      - 8000:8000
    container_name: back
    