export default {
    'Welcome': 'Welcome',
    "Administrator":"Administrator",
    "Bills":"Bills",
    "Customers":"Customers",
    "Record Payments":"Record Payments",
    "Substations":"Substations",
    "Substation":"Substation",
    "Substation Card":"Substation Card",
    "Transformers":"Transformers",
    "Users":"Users",
    "Analytics":"Analytics",
    "Reports":"Reports",
    "Banks":"Banks",
    "Company":"Company",
    "Inventory":"Inventory",
    "Guest":"Guest",
    "Language:":"Language:",
    "Log out":"Log out",
    "Operator":"Operator",
    "Manager":"Manager",
    "Company Overview":"Company Overview",
    "Name":"Name",
    "Surname":"Surname",
    "Address":"Address",
    "Type":"Type",
    "Shipping way":"Shipping way",
    "Legal":"Legal",
    "Natural":"Natural",
    "Online":"Online",
    "Physical":"Physical",
    "True":"True",
    "False": "False",
    "true":"true",
    "false": "false",
    "Active":"Active",
    "Longitud":"Longitud",
    "Latitud":"Latitud",
    "Select the position of the substation":"Select the position of the substation",
    "Hide map":"Hide map",
    "Show map":"Show map",
    "The id will be assigned automatically":"The id will be assigned automatically",
    "Identification":"Identification",
    "City":"City",
    "The Bank was successfully updated":"The Bank was successfully updated",
    "All fields are required":"All fields are required",
    "The Bank was successfully created":"The Bank was successfully created",
    "Apartment card":"Apartment card",
    "Contract number":"Contract number",
    "Stratum":"Stratum",
    "Electricitymeter":"Electricitymeter",
    "New Apartament card":"New Apartament card",
    "Edit Apartament card":"Edit Apartament card",
    "Search the address in the map":"Search the address in the map",
    "Select the position of the Apartment":"Select the position of the Apartment"
};