export default {
    'Welcome': 'Welcome',
    "Administrator":"Administrator",
    "Bills":"Bills",
    "Customers":"Customers",
    "Record Payments":"Record Payments",
    "Substations":"Substations",
    "Substation":"Substation",
    "Substation Card":"Substation Card",
    "Transformers":"Transformers",
    "Users":"Users",
    "Analytics":"Analytics",
    "Reports":"Reports",
    "Banks":"Banks",
    "Company":"Company",
    "Inventory":"Inventory",
    "Guest":"Guest",
    "Language:":"Language:",
    "Log out":"Log out",
    "Operator":"Operator",
    "Manager":"Manager",
    "Company Overview":"Company Overview",
    "Name":"Name",
    "Surname":"Surname",
    "Address":"Address",
    "Type":"Type",
    "Shipping way":"Shipping way",
    "Legal":"Legal",
    "Natural":"Natural",
    "Online":"Online",
    "Physical":"Physical",
    "True":"True",
    "False": "False",
    "true":"true",
    "false": "false",
    "Active":"Active",
    "Longitud":"Longitud",
    "Latitud":"Latitud",
    "Select the position of the substation":"Select the position of the substation",
    "Hide map":"Hide map",
    "Show map":"Show map",
    "The id will be assigned automatically":"The id will be assigned automatically",
    "Identification":"Identification",
    "City":"City",
    "The Bank was successfully updated":"The Bank was successfully updated",
    "All fields are required":"All fields are required",
    "The Bank was successfully created":"The Bank was successfully created",
    "Exit":"Exit",
    "Save to PDF":"Save to PDF",
    "Close": "Close",
    "print pdf": "print pdf",
    "add apartment" : "add apartment",
    "Apartment card":"Apartment card",
    "Contract number":"Contract number",
    "Stratum":"Stratum",
    "Electricitymeter":"Electricitymeter",
    "New Apartament card":"New Apartament card",
    "Edit Apartament card":"Edit Apartament card",
    "Search the address in the map":"Search the address in the map",
    "Select the position of the Apartment":"Select the position of the Apartment",
    "Tension Level" : "Tension Level",
    "Transformer Card" : "Transformer Card",
    "Transformer": "Transformer",
    "Substation Id": "Substation Id",
    "Substation Address" : "Substation Address",    
    "Portuguese":"Portuguese",
    "Spanish":"Spanish",
    "German":"German",
    "English":"English",
    "Log In":"Log In",
    "User ID" :"User ID",
    "Password":"Password",
    "Welcome to":"Welcome to",
    "Please select the kind of user that you are":"Please select the kind of user that you are",
    "Consult services bill":"Check your service invoice online",
    "Select option to consult":"Select the option with which you want to consult and pay:",
    "With document":"With document",
    "With contract":"With contract",
    "Info terms":"By pressing CONSULT you are accepting the terms and conditions",
    "Consult":"CONSULT",
    "Document or NIT":"Document or NIT",
    "Income":"Income",
    "Employees":"Employees",
    "Clients":"Clients",
    "Assets":"Assets",
    //Record Payments
    "Consult RP":"Consult the record payment",
    "Instruc":"Enter customer's id",
    "Id pay": "Payment Identifier ",
    "Paid": "You paid the amount of: ",
    "Date pay": "You paid on the date ",
    "Bill paid": "You paid the invoice number ",
    "No client with id":"There is no client with that identifier",
    //Pay Bill
    "Make payment": "Make payment",
    "Search Bill":"Enter the identifier of the invoice to be paid",
    "Pay": "Pay",
    "No bill with id":"There is no invoice with that identifier",
    "Search bill no resuslt":"Search produced no results. Try again",
    "Pay Bill title":"Pay invoice",
    "Bill":"Bill ",
    "Get payment":"Charges the customer the amount of $",
    "Change payment":"If necessary, deliver the change to the customer",
    "Cancel":"Cancel",
    "Create pay":"Generate payment",
    "Paid bill":"Invoice paid",
    "Bill already paid":"This invoice has already been paid",
    "Bill identifier":"Invoice identifier",
};