export default {
    'Welcome': 'Bienvenido',
    "Administrator":"Administrador",
    "Bills":"Facturas",
    "Customers":"Clientes",
    "Record Payments":"Historial de Pagos",
    "Substations":"Subestaciones",
    "Substation":"Subestacion",
    "Substation Card":"Tarjeta de Subestacion",
    "Transformers":"Transformadores",
    "Users":"Usuarios",
    "Analytics":"Estadisticas",
    "Reports":"Reportes",
    "Banks":"Bancos",
    "Company":"Compañia",
    "Inventory":"Inventario",
    "Guest":"Invitado",
    "Language:":"Lenguaje:",
    "Log out":"Cerrar Sesion",
    "Operator":"Operador",
    "Manager":"Gerente",
    "Company Overview":"Resumen de la compañía",
    "Name":"Nombre",
    "Surname":"Apellido",
    "Type":"Tipo",
    "Shipping way":"Metodo de envio",
    "Legal":"Juridica",
    "Natural":"Natural",
    "Online":"En linea",
    "Physical":"Fisica",
    "True":"Verdadero",
    "False":"Falso",
    "Active":"Activo",
    "Address":"Direccion",
    "Longitud":"Longitud",
    "Latitud":"Latitud",
    "Select the position of the substation":"Seleccione la posicion de la subestacion",
    "Hide map":"Ocultar mapa",
    "Show map":"Mostrar mapa",
    "The id will be assigned automatically":"El Id sera asignado automaticamente",
    "Identification":"Identificacion",
    "City":"Ciudad",
    "The Bank was successfully updated":"El banco fue actualizado exitosamente!",
    "All fields are required":"Todos los campos son requeridos",
    "The Bank was successfully created":"El banco fue creado exitosamente"
};