export default {
    'Welcome': 'Bienvenido',
    "Administrator":"Administrador",
    "Bills":"Facturas",
    "Customers":"Clientes",
    "Record Payments":"Historial de Pagos",
    "Substations":"Subestaciones",
    "Substation":"Subestacion",
    "Substation Card":"Tarjeta de Subestacion",
    "Transformers":"Transformadores",
    "Users":"Usuarios",
    "Analytics":"Estadisticas",
    "Reports":"Reportes",
    "Banks":"Bancos",
    "Company":"Compañia",
    "Inventory":"Inventario",
    "Guest":"Invitado",
    "Language:":"Lenguaje:",
    "Log out":"Cerrar Sesion",
    "Operator":"Operador",
    "Manager":"Gerente",
    "Company Overview":"Resumen de la compañía",
    "Name":"Nombre",
    "Surname":"Apellido",
    "Type":"Tipo",
    "Shipping way":"Metodo de envio",
    "Legal":"Juridica",
    "Natural":"Natural",
    "Online":"En linea",
    "Physical":"Fisica",
    "True":"Verdadero",
    "False":"Falso",
    "true":"Verdadero",
    "false":"Falso",
    "Active":"Activo",
    "Address":"Direccion",
    "Longitud":"Longitud",
    "Latitud":"Latitud",
    "Select the position of the substation":"Seleccione la posicion de la subestacion",
    "Hide map":"Ocultar mapa",
    "Show map":"Mostrar mapa",
    "The id will be assigned automatically":"El Id sera asignado automaticamente",
    "Identification":"Identificacion",
    "City":"Ciudad",
    "The Bank was successfully updated":"El banco fue actualizado exitosamente!",
    "All fields are required":"Todos los campos son requeridos",
    "The Bank was successfully created":"El banco fue creado exitosamente",
    "Exit":"Salir",
    "Save to PDF":"Guardar en PDF",
    "Close": "Cerrar",
    "print pdf": "imprimir pdf",
    "add apartment" : "agregar apartamento",
    "Apartment card":"Tarjeta de apartamento",
    "Contract number":"Numero de contrato",
    "Stratum":"Estrato",
    "Electricitymeter":"Contador",
    "New Apartament card":"Nueva tarjeta de Apartamento",
    "Edit Apartament card":"Editar tarjeta del Apartamento",
    "Search the address in the map":"Buscar la direccion en el mapa",
    "Select the position of the Apartment":"Selecciona la posicion del apartamento",
    "Tension Level" : "Nivel de Tensión",
    "Transformer Card" : "Ficha de Transformador",
    "Transformer": "Transformador",
    "Substation Id": "Subestacion Id",
    "Substation Address" : "Dirección de Subestacion",
    "Portuguese":"Portugues",
    "German":"Aleman",
    "Spanish":"Español",
    "English":"Ingles",
    "Log In":"Iniciar Sesion",
    "User ID" :"Identificacion",
    "Password":"Contraseña",
    "Welcome to":"Bienvenidos a",
    "Please select the kind of user that you are":"Por favor seleccione el tipo de usuario que es",
    "Consult services bill":"Consulta tu factura de servicios en linea",
    "Select option to consult":"Selecciona la opción con la que deseas consultar y pagar:",
    "With document":"Por documento",
    "With contract":"Por contrato",
    "Info terms":"Al presionar CONSULTAR estás aceptando los términos y condiciones",
    "Consult":"CONSULTAR",
    "Document or NIT":"Documento o NIT",
    "Income":"Ingresos",
    "Employees":"Empleados",
    "Assets":"Activos",
    "Clients":"Clientes",
    //Record Payments
    "Consult RP":"Consulta el registro de pagos",
    "Instruc":"Ingresa el id del cliente",
    "Id pay": "Identificador de Pago ",
    "Paid": "Pagaste la cantidad de: ",
    "Date pay": "Pagaste en la fecha ",
    "Bill paid": "Pagaste la factura número ",
    "No client with id":"No hay cliente con ese id",
    //Pay Bill
    "Make payment": "Realizar pago",
    "Search Bill":"Ingresa el identificador de la factura a ser pagada",
    "Pay": "Pagar",
    "No bill with id":"No hay factura con ese id",
    "Search bill no resuslt":"La busqueda no produjo resultados. Intente nuevamente",
    "Pay Bill title":"Pagar factura",
    "Bill":"Factura ",
    "Get payment":"Cobra al cliente la cantidad de $",
    "Change payment":"En caso de ser necesario, entrega el cambio al cliente",
    "Cancel":"Cancelar",
    "Create pay":"Generar pago",
    "Paid bill":"Factura pagada",
    "Bill already paid":"Esta factura ya fue pagada",
    "Bill identifier":"Identificador de factura",
};