export default {
    'Welcome': 'Bem-vindo',
    "Administrator":"Administrador",
    "Bills":"Contas",
    "Customers":"Clientes",
    "Record Payments":"Registro de Pagamentos",
    "Substations":"Subestações",
    "Substation":"Subestaçõe",
    "Substation Card":"Cartão de subestação",
    "Transformers":"Transformadores",
    "Users":"Usuários",
    "Analytics":"Analytics",
    "Reports":"Relatórios",
    "Banks":"Bancos",
    "Company":"Empresa",
    "Inventory":"Inventário",
    "Guest":"Convidado",
    "Language:":"Língua:",
    "Log out":"Sair",
    "Operator":"Operador",
    "Manager":"Gerente",
    "Company Overview":"Visão geral da empresa",
    "Name":"Nome",
    "Surname":"Sobrenome",
    "Type":"Tipo",
    "Shipping way":"Modo de envio",
    "Legal":"Legal",
    "Natural":"Natural",
    "Online":"Online",
    "Physical":"Fisica",
    "True":"Verdade",
    "False":"Falso",
    "true":"Verdade",
    "false":"Falso",
    "Active":"Ativo",
    "Address":"Endereço",
    "Longitud":"Longitude",
    "Latitud":"Latitude",
    "Select the position of the substation":"Selecione a posição da subestação",
    "Hide map":"Encobrir mapa",
    "Show map":"Mostrar mapa",
    "The id will be assigned automatically":"O id será atribuído automaticamente",
    "Identification":"Identificação",
    "City":"Cidade",
    "The Bank was successfully updated":"O Banco foi atualizado com sucesso!",
    "All fields are required":"Todos os campos são necessários",
    "The Bank was successfully created":"O Banco foi criado com sucesso!",
    "Apartment card":"Cartão de apartamento",
    "Contract number":"Número do contrato",
    "Stratum":"Estrato",
    "Electricitymeter":"Medidor de eletricidade",
    "New Apartament card":"Cartão Novo Apartamento",
    "Edit Apartament card":"Editar cartão do apartamento",
    "Search the address in the map":"Pesquise o endereço no mapa",
    "Select the position of the Apartment":"Selecione a posição do apartamento",
    "Portuguese":"Português",
    "German":"Alemão",
    "Spanish":"Espanhol",
    "English":"Inglês",
    "Log In":"Conecte-se",
    "User ID":"identificação",
    "Password":"Senha"
};



