# Generated by Django 3.0.3 on 2020-02-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'natural'), ('j', 'juridica')], default=('N',), max_length=1)),
                ('shipping_way', models.CharField(choices=[('L', 'Linea'), ('F', 'Fisico'), ('E', 'Email')], default='L', max_length=1)),
            ],
        ),
    ]
