# Generated by Django 3.0.3 on 2020-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='shipping_way',
            field=models.CharField(choices=[('E', 'Email'), ('F', 'Fisico'), ('L', 'Linea')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('j', 'juridica'), ('N', 'natural')], default=('N',), max_length=1),
        ),
    ]
