# Generated by Django 3.0.3 on 2020-02-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20200220_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('N', 'natural'), ('j', 'juridica')], default=('N',), max_length=1),
        ),
    ]
